# config.yaml

jupyterhub:
  singleuser:
    image:
      name: "gcr.io/dask-demo-182016/dask-ml-pydata"
      tag: "ef7b4f"
    defaultUrl: "/lab"
    cmd: jupyter-labhub
    serviceAccountName: daskkubernetes
  prePuller:
    hook:
      enabled: false

# jupyter:
#   image:
#     repository: "gcr.io/dask-demo-182016/dask-ml-pydata"
#     tag: "ef7b4f"

#   affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#           - matchExpressions:
#             - key: cloud.google.com/gke-preemptible
#               operator: DoesNotExist

# scheduler:
#   image:
#     repository: "gcr.io/dask-demo-182016/dask-ml-pydata"
#     tag: "ef7b4f"
#   affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#           - matchExpressions:
#             - key: cloud.google.com/gke-preemptible
#               operator: DoesNotExist

# worker:
#   image:
#     repository: "gcr.io/dask-demo-182016/dask-ml-pydata"
#     tag: "ef7b4f"

#   replicas: 2
#   resources:
#     limits:
#       cpu: 2
#       memory: 7.5G
#     requests:
#       cpu: 2
#       memory: 7.5G

#   affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#           - matchExpressions:
#             - key: cloud.google.com/gke-preemptible
#               operator: In
#               values:
#                 - "true"
#   tolerations:
#      - key: "preemptible"
#        operator: "Equal"
#        value: "true"
#        effect: "NoSchedule" 
