# config.yaml

jupyterhub:
  singleuser:
    image:
      name: "gcr.io/dask-demo-182016/dask-ml-pydata"
      tag: "0c01c5"
    defaultUrl: "/lab"
    cmd: jupyter-labhub
    serviceAccountName: daskkubernetes
    # lifecycleHooks:
    #     postStart:
    #       exec:
    #         command:
    #           - "sh"
    #           - "-c"
    #           - >
    #             mkdir -p /home/jovyan/.config/dask && \
    #             cp /tmp/dask_config.yaml /home/jovyan/.config/dask/dask_config.yaml && \
    #             cp -R /tmp/examples examples

    storage:
      capacity: 40Gi

  prePuller:
    hook:
      enabled: false
