# config.yaml

jupyterhub:
  singleuser:
    image:
      name: "gcr.io/dask-demo-182016/dask-ml-pydata"
      tag: "883c90"
    defaultUrl: "/lab"
    cmd: jupyter-labhub
    serviceAccountName: daskkubernetes
    lifecycleHooks:
        postStart:
          exec:
            command:
              - "sh"
              - "-c"
              - >
                mkdir -p /home/jovyan/.config/dask
                cp /tmp/dask_config.yaml /home/jovyan/.config/dask/dask_config.yaml
    storage:
      capacity: 40Gi

  hub:
    extraConfig:
      jupyterlab: |
        c.Spawner.cmd = ['jupyter-labhub']
 
  prePuller:
    hook:
      enabled: false
